export const ANIMATED_PATTERNS = [
  'sakura-petals',
  'floating-shields',
  'bitcoin-particles',
  'stacking-blocks',
  'digital-rain',
  'constellation',
  'sanctuary-logo',
  'snowfall',
  'fireflies',
  'ink-drops',
  'rippling-water',
  'falling-leaves',
  'embers-rising',
  'gentle-rain',
  'northern-lights',
  'koi-shadows',
  'bamboo-sway',
  'lotus-bloom',
  'floating-lanterns',
  'moonlit-clouds',
  'tide-pools',
  'train-station',
  'serene-meadows',
  'still-ponds',
  'desert-dunes',
  'mountain-mist',
  'duckling-parade',
  'bunny-meadow',
  'stargazing',
  'lavender-fields',
  'zen-sand-garden',
  'sunset-sailing',
  'raindrop-window',
  'butterfly-garden',
  'dandelion-wishes',
  'misty-valley',
  'gentle-waves',
  'jellyfish-drift',
  'wind-chimes',
  'sakura-redux',
  'sats-symbol',
  'fireworks',
  'hash-storm',
  'ice-crystals',
  'autumn-wind',
  'smoke-calligraphy',
  'breath',
  'mycelium-network',
  'oil-slick',
  'bioluminescent-beach',
  'volcanic-islands',
  'tidal-patterns',
  'eclipse',
  'paper-boats',
  'paper-airplanes',
  'thunderstorm',
] as const;

export type AnimatedPatternId = (typeof ANIMATED_PATTERNS)[number];

const animatedPatternSet = new Set<string>(ANIMATED_PATTERNS);

export function isAnimatedPattern(pattern: string): pattern is AnimatedPatternId {
  return animatedPatternSet.has(pattern);
}
