/**
 * Hardware Wallet Verified Vectors
 *
 * These vectors are generated by actual hardware wallets and serve as the
 * ultimate ground truth for address derivation. If our implementation
 * produces different addresses than hardware wallets, FUNDS WILL BE LOST.
 *
 * To add new vectors:
 * 1. Use the seed mnemonic on a hardware wallet
 * 2. Export addresses or verify them on-device
 * 3. Record the device model, firmware version, and date verified
 * 4. Add to the appropriate section below
 *
 * DO NOT MODIFY EXISTING VECTORS without re-verification on hardware.
 */

export interface HardwareWalletVector {
  // Verification provenance
  device: string; // e.g., "Coldcard Mk4", "Ledger Nano S Plus", "Trezor Model T"
  firmware: string; // e.g., "5.2.0"
  verifiedDate: string; // ISO date: "2024-01-15"
  verifiedBy?: string; // Optional: who verified this

  // Derivation parameters
  mnemonic: string; // The seed used (should be test mnemonics only!)
  passphrase?: string; // BIP-39 passphrase if used
  network: 'mainnet' | 'testnet';
  scriptType: 'legacy' | 'nested_segwit' | 'native_segwit' | 'taproot';
  accountIndex: number;

  // Expected xpub at account level
  expectedXpub: string;
  derivationPath: string; // Full path to xpub, e.g., "m/84'/0'/0'"

  // Expected addresses
  addresses: {
    index: number;
    receive: string;
    change: string;
  }[];
}

export interface MultisigHardwareWalletVector {
  // Verification provenance
  devices: {
    device: string;
    firmware: string;
    verifiedDate: string;
  }[];

  // Multisig configuration
  threshold: number;
  totalSigners: number;
  network: 'mainnet' | 'testnet';
  scriptType: 'p2sh' | 'p2sh_p2wsh' | 'p2wsh';

  // Per-device xpubs (in order of device verification)
  signers: {
    mnemonic: string;
    derivationPath: string;
    xpub: string;
  }[];

  // Expected multisig addresses
  addresses: {
    index: number;
    receive: string;
    change: string;
  }[];
}

/**
 * SINGLE-SIG HARDWARE WALLET VECTORS
 *
 * Verified on actual hardware devices.
 * Add your hardware wallet verification results here.
 */
export const HARDWARE_WALLET_SINGLESIG_VECTORS: HardwareWalletVector[] = [
  // Example structure - replace with actual hardware wallet exports
  // {
  //   device: 'Coldcard Mk4',
  //   firmware: '5.2.0',
  //   verifiedDate: '2024-01-15',
  //   verifiedBy: 'Your Name',
  //   mnemonic: 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
  //   network: 'testnet',
  //   scriptType: 'native_segwit',
  //   accountIndex: 0,
  //   expectedXpub: 'tpubDC5FSnBiZDMmhiuCmWAYsLwgLYrrT9rAqvTySfuCCrgsWz8wxMXUS9Tb9iVMvcRbvFcAHGkMD5Kx8koh4GquNGNTfohfk7pgjhaPCdXpoba',
  //   derivationPath: "m/84'/1'/0'",
  //   addresses: [
  //     { index: 0, receive: 'tb1q6rz28mcfaxtmd6v789l9rrlrusdprr9pqcpvkl', change: 'tb1q9u62588spffmq4dzjxsr5l297znf3z6jkgnhsw' },
  //     { index: 1, receive: 'tb1qd7spv5q28348xl4myc8zmh983w5jx32cjhkn97', change: 'tb1qkwgskuzmmwwvqajnyr7yp9van7gde6csqmldxs' },
  //   ],
  // },
];

/**
 * MULTISIG HARDWARE WALLET VECTORS
 *
 * Verified across multiple hardware devices working together.
 * Critical for ensuring multisig address compatibility.
 */
export const HARDWARE_WALLET_MULTISIG_VECTORS: MultisigHardwareWalletVector[] = [
  // Example structure - replace with actual hardware wallet exports
  // {
  //   devices: [
  //     { device: 'Coldcard Mk4', firmware: '5.2.0', verifiedDate: '2024-01-15' },
  //     { device: 'Ledger Nano S Plus', firmware: '1.1.0', verifiedDate: '2024-01-15' },
  //     { device: 'Trezor Model T', firmware: '2.6.3', verifiedDate: '2024-01-15' },
  //   ],
  //   threshold: 2,
  //   totalSigners: 3,
  //   network: 'testnet',
  //   scriptType: 'p2wsh',
  //   signers: [
  //     {
  //       mnemonic: 'abandon...',
  //       derivationPath: "m/48'/1'/0'/2'",
  //       xpub: 'tpub...',
  //     },
  //     // ... more signers
  //   ],
  //   addresses: [
  //     { index: 0, receive: 'tb1q...', change: 'tb1q...' },
  //   ],
  // },
];

/**
 * Instructions for adding hardware wallet vectors:
 *
 * COLDCARD:
 * 1. Load test seed on Coldcard
 * 2. Navigate to Advanced > Export Wallet > Generic JSON
 * 3. Export to SD card
 * 4. Extract xpub and addresses
 * 5. Verify first few addresses match on-device display
 *
 * LEDGER:
 * 1. Initialize with test seed
 * 2. Use Ledger Live or HWI to export xpub
 * 3. Verify addresses using the device display
 *
 * TREZOR:
 * 1. Initialize with test seed
 * 2. Use Trezor Suite or HWI to export xpub
 * 3. Verify addresses using the device display
 *
 * IMPORTANT: Always use test seeds, never production seeds!
 * The standard test seed is:
 * "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
 */
