#!/bin/bash
#
# Sanctuary Setup Script
#
# Generates all required secrets and creates .env file
# Run this once before first `docker compose up`
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════╗"
echo "║           Sanctuary Setup Script                  ║"
echo "╚═══════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Warning: .env file already exists.${NC}"
    read -p "Overwrite with new secrets? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Your existing .env is unchanged."
        exit 0
    fi
    echo
fi

# Generate secure random strings
generate_secret() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

generate_password() {
    openssl rand -base64 16 | tr -d '/+='
}

echo -e "${GREEN}Generating secure secrets...${NC}"

JWT_SECRET=$(generate_secret)
ENCRYPTION_KEY=$(generate_secret)
GATEWAY_SECRET=$(generate_secret)
POSTGRES_PASSWORD=$(generate_password)

echo "  - JWT_SECRET: generated"
echo "  - ENCRYPTION_KEY: generated"
echo "  - GATEWAY_SECRET: generated"
echo "  - POSTGRES_PASSWORD: generated"
echo

# Create .env file
echo -e "${GREEN}Creating .env file...${NC}"

cat > "$ENV_FILE" << EOF
# Sanctuary Bitcoin Wallet - Environment Configuration
# Generated by setup.sh on $(date)
#
# IMPORTANT: Keep this file secure and never commit to version control

# ============================================
# REQUIRED SECRETS (auto-generated)
# ============================================

# JWT secret for authentication tokens
JWT_SECRET=$JWT_SECRET

# Encryption key for sensitive data (node passwords, etc.)
ENCRYPTION_KEY=$ENCRYPTION_KEY

# Gateway secret for internal service communication
GATEWAY_SECRET=$GATEWAY_SECRET

# PostgreSQL database password
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ============================================
# PORTS (defaults are usually fine)
# ============================================

# HTTPS port for web interface
HTTPS_PORT=8443

# HTTP port (redirects to HTTPS)
HTTP_PORT=8080

# Gateway port for mobile app
GATEWAY_PORT=4000

# ============================================
# OPTIONAL - Bitcoin Network
# ============================================

# Options: mainnet, testnet, regtest
BITCOIN_NETWORK=mainnet

# ============================================
# OPTIONAL - Logging
# ============================================

# Options: debug, info, warn, error
LOG_LEVEL=info
EOF

echo -e "${GREEN}Setup complete!${NC}"
echo
echo -e "${BLUE}Your .env file has been created with secure random secrets.${NC}"
echo
echo "Next steps:"
echo "  1. Generate SSL certificates (if not done):"
echo "     cd docker/nginx/ssl && ./generate-certs.sh localhost"
echo
echo "  2. Start Sanctuary:"
echo "     docker compose up -d"
echo
echo "  3. Open https://localhost:8443"
echo
echo -e "${YELLOW}Note: Your secrets are stored in .env - keep this file secure!${NC}"
